#ifndef CONSTANTES_H
#define CONSTANTES_H
#include <irrlicht.h>

const irr::f32 WALK_VITESSE_ENEMY = 1.0f;
const irr::f32 RUN_VITESSE_ENEMY = 1.85f;
const irr::f32 DISTANCE_MIN_TO_CHASE_MAIN_CHARACTER= 300;
const irr::u32 TIME_BEFORE_CHANGING_RANDOM_WALK_DIRECTION = 500;

#endif // CONSTANTES_H
